local T = require("ngx_mock")
local cors = require("cors")

T.test("defaults: localhost / loopback / null allowed, others not", function()
    cors._configure(nil)
    T.eq(cors.match("http://localhost:3000"), "http://localhost:3000")
    T.eq(cors.match("https://localhost"), "https://localhost")
    T.eq(cors.match("http://127.0.0.1:8080"), "http://127.0.0.1:8080")
    T.eq(cors.match("null"), "null")
    T.eq(cors.match("https://e2ee-local-proxy.chutes.dev:8443"), "https://e2ee-local-proxy.chutes.dev:8443")
    T.eq(cors.match("https://evil.example"), nil)
    T.eq(cors.match("http://localhost.evil.example"), nil, "suffix trick")
    T.eq(cors.match("http://localhost:3000.evil.example"), nil)
    T.eq(cors.match(""), nil)
    T.eq(cors.match(nil), nil)
end)

T.test("custom list: exact and wildcard entries", function()
    cors._configure("https://app.example.com, https://*.example.org,http://localhost:*")
    T.eq(cors.match("https://app.example.com"), "https://app.example.com")
    T.eq(cors.match("https://APP.example.com"), "https://APP.example.com", "case-insensitive")
    T.eq(cors.match("https://x.example.org"), "https://x.example.org")
    T.eq(cors.match("https://example.org"), nil, "wildcard needs a subdomain")
    T.eq(cors.match("http://localhost:5173"), "http://localhost:5173")
    T.eq(cors.match("http://localhost"), nil, "custom list replaces defaults")
    T.eq(cors.match("null"), nil)
end)

T.test("'*' restores allow-any", function()
    cors._configure("*")
    T.eq(cors.match("https://anything.example"), "https://anything.example")
end)

T.test("apply sets headers for allowed origins and clears them otherwise", function()
    cors._configure(nil)
    T.truthy(cors.apply("http://localhost:3000", true))
    T.eq(ngx.header["Access-Control-Allow-Origin"], "http://localhost:3000")
    T.eq(ngx.header["Vary"], "Origin")
    T.eq(ngx.header["Access-Control-Max-Age"], "86400")
    T.truthy(ngx.header["Access-Control-Allow-Headers"]:find("X-Route-Mode", 1, true))
    T.truthy(cors.apply("http://localhost:3000", true, "x-stainless-os, x-custom"))
    T.eq(ngx.header["Access-Control-Allow-Headers"], "x-stainless-os, x-custom", "requested headers echoed")
    T.truthy(cors.apply("http://localhost:3000", true, "bad\nheader"))
    T.truthy(ngx.header["Access-Control-Allow-Headers"]:find("Authorization", 1, true), "unsafe value -> fallback")

    ngx.header["Access-Control-Allow-Origin"] = "*" -- as if upstream set it
    T.falsy(cors.apply("https://evil.example", false))
    T.eq(ngx.header["Access-Control-Allow-Origin"], nil, "upstream wildcard removed")
end)

T.finish("cors")
