local T = require("ngx_mock")
local metrics = require("metrics")

T.test("counters, gauges, histograms render in exposition format", function()
    metrics.reset()
    metrics.inc("e2ee_requests_total", { path = "/v1/chat/completions", mode = "agent", outcome = "ok" })
    metrics.inc("e2ee_requests_total", { path = "/v1/chat/completions", mode = "agent", outcome = "ok" }, 2)
    metrics.set("e2ee_build_info", { native = 'x "y"' }, 1)
    metrics.observe("e2ee_ttft_seconds", { mode = "agent" }, 0.3)
    metrics.observe("e2ee_ttft_seconds", { mode = "agent" }, 4)
    metrics.observe("e2ee_ttft_seconds", { mode = "agent" }, 1000)
    local text = metrics.render()
    T.truthy(text:find("# TYPE e2ee_requests_total counter\n", 1, true))
    T.truthy(text:find('e2ee_requests_total{mode="agent",outcome="ok",path="/v1/chat/completions"} 3\n', 1, true),
             "labels sorted, value summed")
    T.truthy(text:find('e2ee_build_info{native="x \\"y\\""} 1\n', 1, true), "label escaping")
    T.truthy(text:find('e2ee_ttft_seconds_bucket{mode="agent",le="0.25"} 0\n', 1, true))
    T.truthy(text:find('e2ee_ttft_seconds_bucket{mode="agent",le="0.5"} 1\n', 1, true))
    T.truthy(text:find('e2ee_ttft_seconds_bucket{mode="agent",le="5"} 2\n', 1, true))
    T.truthy(text:find('e2ee_ttft_seconds_bucket{mode="agent",le="+Inf"} 3\n', 1, true))
    T.truthy(text:find('e2ee_ttft_seconds_sum{mode="agent"} 1004.3\n', 1, true))
    T.truthy(text:find('e2ee_ttft_seconds_count{mode="agent"} 3\n', 1, true))
end)

T.test("unknown metric names and wrong kinds are ignored, not errors", function()
    metrics.reset()
    metrics.inc("does_not_exist", nil, 1)
    metrics.observe("e2ee_requests_total", nil, 1) -- counter, not histogram
    metrics.inc("e2ee_ttft_seconds", nil, 1)       -- histogram, not counter
    metrics.observe("e2ee_ttft_seconds", nil, "x")
    T.eq(metrics.render(), "", "nothing rendered when no series exist")
end)

T.test("unlabelled series", function()
    metrics.reset()
    metrics.inc("e2ee_stream_chunks_total", nil, 5)
    metrics.observe("e2ee_discovery_seconds", nil, 0.2)
    local text = metrics.render()
    T.truthy(text:find("e2ee_stream_chunks_total 5\n", 1, true))
    T.truthy(text:find('e2ee_discovery_seconds_bucket{le="0.25"} 1\n', 1, true))
    T.truthy(text:find("e2ee_discovery_seconds_count 1\n", 1, true))
end)

T.test("collectors run before render", function()
    metrics.reset()
    metrics.add_collector(function()
        metrics.set("e2ee_build_info", { k = "collector" }, 1)
    end)
    T.truthy(metrics.render():find('e2ee_build_info{k="collector"} 1', 1, true))
end)

T.finish("metrics")
